local autocmd = vim.api.nvim_create_autocmd

-- autocmd(
-- 	'CursorHold',
-- 	{
-- 		pattern = '*',
-- 		callback = function(ev)
-- 			require('nvim-lightbulb').update_lightbulb()
-- 		end,
-- 	}
-- )
--
-- autocmd(
-- 	'CursorHoldI',
-- 	{
-- 		pattern = '*',
-- 		callback = function(ev)
-- 			require('nvim-lightbulb').update_lightbulb()
-- 		end,
-- 	}
-- )
--
