ncvim.plugin({
  'm4xshen/hardtime.nvim',
  dependencies = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim",
  },
  opts = {
    -- Add "oil" to the disabled_filetypes
    restriction_mode = "hint", -- block or hint
    restricted_keys = {
      ["h"] = {},
      ["j"] = {},
      ["k"] = {},
      ["l"] = {},
      ["+"] = { "n", "x" },
      ["gj"] = { "n", "x" },
      ["gk"] = { "n", "x" },
      ["<C-M>"] = { "n", "x" },
      ["<C-N>"] = { "n", "x" },
      ["<C-P>"] = { "n", "x" },
    },
    disabled_filetypes = {
      "NvimTree",
      "TelescopePrompt",
      "aerial",
      "alpha",
      "checkhealth",
      "dapui*",
      "Diffview*",
      "Dressing*",
      "help",
      "httpResult",
      "lazy",
      "lspinfo",
      "Neogit*",
      "mason",
      "neotest%-summary",
      "Neotest Summary",
      "minifiles",
      "neo%-tree*",
      "netrw",
      "noice",
      "notify",
      "prompt",
      "qf",
      "query",
      "oil",
      "undotree",
      "trouble",
      "Trouble",
      "fugitive",
      "Outline",

      "dbui",
      "dbout",
    },
  },
})
