ncvim.plugin({
  'm4xshen/hardtime.nvim',
  dependencies = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim",
  },
  opts = {
    -- Add "oil" to the disabled_filetypes
    disabled_filetypes = {
      "NvimTree",
      "TelescopePrompt",
      "aerial",
      "alpha",
      "checkhealth",
      "dapui*",
      "Diffview*",
      "Dressing*",
      "help",
      "httpResult",
      "lazy",
      "lspinfo",
      "Neogit*",
      "mason",
      "neotest%-summary",
      "minifiles",
      "neo%-tree*",
      "netrw",
      "noice",
      "notify",
      "prompt",
      "qf",
      "query",
      "oil",
      "undotree",
      "trouble",
      "Trouble",
      "fugitive",

      "dbui",
      "dbout",
    },
  },
})
