require('plugins_config.mason')
require('plugins_config.treesitter')
require('plugins_config.lualine')
require('plugins_config.nvim_comment')
require('plugins_config.telescope')
require('plugins_config.which_key')
require('plugins_config.vim_prettier')
require('plugins_config.nerdtree')
require('plugins_config.eslint')
require('plugins_config.editorconfig')
require('plugins_config.easymotion')
require('plugins_config.bufferline')
require('plugins_config.gitsigns')
require('plugins_config.autopairs')
require('plugins_config.leetcode')
require('plugins_config.git')
-- require('plugins_config.minimap')
